### ISSUE TITLE
no-access-missing-member throwing when template accessing public properties on parent class

### ISSUE THREAD

**Issue by leosvelperez** [mgechev/codelyzer#285]
I have an Angular 4 app and I have a parent class for my custom components. There I have several public properties and methods which are used in the template of the custom components. The `no-access-missing-member` rule is throwing telling me those properties and methods don't exist on the class declaration.
Below is part of the files I'm using:
```typescript
export class BaseComponent<T> implements ControlValueAccessor {
	disabled: boolean;
	focused: boolean;
	model: T;

        ...
}
```
```typescript
@Component({
	selector: 'rm-input',
	templateUrl: './input.component.html',
	styleUrls: ['./input.component.scss']
})
export class InputComponent extends BaseComponent<string> implements OnChanges {

        ...

}
```
The `InputComponent` template is just using the `disabled`, `focused`, `model` properties and other methods declared on the `BaseComponent`.
The `InputComponent` is not hiding the base properties or methods and even if it was hiding them and using non-public identifier, it should be the `templates-use-public` rule the one throwing the warning.

I'm using the following libs:
```
"@angular/MODULE": "^4.0.1" // several modules
"codelyzer": "^2.1.1"
"tslint": "^4.5.1"
"typescript": "^2.2.2"
```

**Comment by mgechev** [comment]
It's a known issue in version 2. It'll be fixed in version 3 (it already is).

**Comment by trumbitta** [comment]
Hi, version 2 and 3 of what?

**Comment by basst314** [comment]
Hi @mgechev, will this be fixed in a 2.x version aswell?

**Comment by basst314** [comment]
@trumbitta version 2 and 3 of this repo, codelyzer

**Comment by trumbitta** [comment]
@basst314 thanks, I should get more sleep. 😸

**Comment by leosvelperez** [comment]
> It's a known issue in version 2. It'll be fixed in version 3 (it already is).

@mgechev I'm still getting this warning even when I'm now using v3.0.0. Was the fix actually merged?

Thanks!

**Comment by WiseBird** [comment]
@mgechev This is issue is still reproducible on 3.0.1. Please check the repo: https://github.com/WiseBird/codelyzer_285

![screen](https://cloud.githubusercontent.com/assets/1745378/25893664/b7c1fcf0-3589-11e7-8221-88df0daa7162.png)

You can run tslint by `npm run tslint`

**Comment by maartentibau** [comment]
@WiseBird got the same issue as well

**Comment by mscelina** [comment]
@mgechev This issue should be reopen.
I see the issue was fixed and merged to master (master at that time): #238 . During the time master start to be out of sync with this commit. 3.0.0-beta.X versions were released with this. Now, these tags are completely out of sync with master and these tags are not at any branch. These changes were never merged with master and released as 3.0.0.
I didn't looked into the code deeply so I'm not able to say how easy it's to get it back to master.

**Comment by mgechev** [comment]
@mscelina this rule will be removed because the language service and the compiler are responsible for finding & reporting compile-time errors.

**Comment by juanmendes** [comment]
@mgechev I wish this check could be done in tslint, because we don't do aot during development and we end up having to fix problems only when we do a production build which takes a lot longer in our case.

**Comment by mgechev** [comment]
@juanmendes you can use the Angular language service for the purpose. [Here](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) it is.
