### ISSUE TITLE
Auto fix for check-interpolation part of angularWhitespace is broken

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#345]

**Comment by wKoza** [comment]
Fixed by #362

**Comment by Matmo10** [comment]
Just curious, when would 3.1.2 show up on npm?

**Comment by mgechev** [comment]
@Matmo10 I'll try to push it tomorrow.

**Comment by Matmo10** [comment]
Just tried it out, I still get the following issues with the autofix:

```
<div class="item-price">{{swimLaneItem.Price.Value| currency:swimLaneItem.Price.Currency:true}}</div>
```
gets changed to
```
<div class="item-price">{{ swimLaneItem.Price.Valu e| currency:swimLaneItem.Price.Currency:true }}</div>
```

Also this
```
<div class="item-description-content">
   {{itemDescriptionToUse| slice:0:500 }}{{ (itemDescriptionToUse && itemDescriptionToUse.length > 500) ? '&hellip;' : '' }}
</div>
```
gets changed to this: 
```
<div class="item-description-content">
   {{ itemDescriptionToUs e| slice:0:500 }}{{ (itemDescriptionToUse && itemDescriptionToUse.length > 500) ? '&hellip;' : '' }}
</div>
```


Also this
```
<span [hidden]="local.ShippingServiceCost.Value == 0">{{local.ShippingServiceCost.Value|currency:local.ShippingServiceCost.Currency:true}} {{local.ShippingServiceCost.Currency}}</span>
```
gets changed to this:
```
<span [hidden]="local.ShippingServiceCost.Value == 0">{{ local.ShippingServiceCost.Valu e |currency:local.ShippingServiceCost.Currency:true }} {{ local.ShippingServiceCost.Currency }}</span>

```

Is this a separate issue?

**Comment by mgechev** [comment]
The source of this issue seems the `check-pipe` option.
